openapi: 3.0.4
info:
  title: Groschenberry log models
  description: Log models for logging services of groschenberry
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        ci:
          $ref: '#/components/schemas/GrschbrCILogModel'
#        comments:
#          $ref: '#/components/schemas/GrschbrLogModel'
#        files:
#          $ref: '#/components/schemas/GrschbrLogModel'
#        images:
#          $ref: '#/components/schemas/GrschbrLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    GrschbrCILogModel:
      title: Модель лога для микросервиса Groschenberry CI
      type: object
      properties:
        ciType:
          $ref: '#/components/schemas/CIType'
        requestId:
          type: string
        operation:
          $ref: '#/components/schemas/GrschbrLogOperation'
        requestCI:
          oneOf:
            - $ref: '#/components/schemas/CIBLog'
            - $ref: '#/components/schemas/CIDLog'
        requestFilter:
          $ref: '#/components/schemas/CIFilterLog'
        responseCI:
          oneOf:
            - $ref: '#/components/schemas/CIBLog'
            - $ref: '#/components/schemas/CIDLog'
        responseCIs:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/CIBLog'
              - $ref: '#/components/schemas/CIDLog'

    CIType:
      type: string
      enum:
        - basic
        - detail
        - none
    GrschbrLogOperation:
      type: string
      enum:
        - create
        - read
        - update
        - delete
        - search
        - init
        - finish

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    CIBLog:
      title: Модель лога для основной карточки монеты
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        country:
          type: string
        currency:
          type: string
        nominal:
          type: string
        material:
          type: string
        diameter:
          type: number
        startYear:
          type: string
        stopYear:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    CIDLog:
      title: Модель лога для основной карточки монеты
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        issueYear:
          type: string
        mint:
          type: string
        copies:
          type: integer
        cibId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    CIFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string